language: python
group: travis_latest
dist: bionic
sudo: true

env:
    global:
        # prefix before commands - used for wine, there the prefix is "wine"
        - cPREFIX=""
        # command to launch python interpreter (its different on macOs, there we need python3)
        - cPYTHON="python"
        # command to launch pip (its different on macOs, there we need pip3)
        - cPIP="python -m pip"
        # switch off wine fix me messages
        - WINEDEBUG=fixme-all
        # mypy path
        - MYPYPATH="./lib_platform/3rd_party_stubs"
        # package name
        - PACKAGE_NAME="lib_platform"
        # the registered CLI Command
        - CLI_COMMAND="lib_platform"
        # the source file for rst_include (rebuild rst file includes)
        - RST_INCLUDE_SOURCE="./.docs/README_template.rst"
        # the target file for rst_include (rebuild rst file includes)
        - RST_INCLUDE_TARGET="./README.rst"
        # secure environment variable
        - secure: "IDAldo6HWLAFHnQg4SRyMO4og923nEjeQ/jeOeFUhvgb8/p8Sq01NZR+CH6EC/YRucTjbuBwociJXgQ88hkYprczbWGiijU0MgV/iiRPHd0/f8ZLOTXsOKK81pKV1wcrZMOsqRwwXCjRZHRr2dwK7kJKlV/5p/ESFI9ZscMZrOllS/vEwoPkyWo8rkMjV/oVvC9N8LENvCDjVseODYBXKMpN9TmrICIghiqnndNU0zdOUmNUqquQajxWRiCfowktkmPBkZpJvCDRm6TEgckVHdnczZE4Hzm8SIqEnQK/FAvy+9N65dbH7yiKufTBBdsQrwtwH1+CAAlIbeWnGtezOSON9zRkJYAjeeE1/ax28coh0NiIg0hNCzSawEjp0mVJnvwYDpW06szvBURaOYtCz9FZ8//Ql5xIKCM9IxX3FMiwhoEKHsmbkYEc5KmljkBBNaKOoxI8rFN26XvqoI9y2aRR7I/fFWxfFiIgVsRo1CL1qFhl+R0dnHbNK0abcGLQ6mRmvqXvQb3tW67So13NBueLfBibARR6uE7lh27JG0rLa92Xez2TPBr0mUOS4QDyrNNXv94LHUzO6rrSO3ZCXqXadqX340EcB9J8TG7a6jLp6R03uLCeGCda7ZWpF/9jbD4iAsDExCb+twwfaN0FCKxYn0VTDFLcJRHv2l4wIGM="  # CC_TEST_REPORTER_ID.secret
        - secure: "wK8WmNhbVEkbI8V3vSGKFtme/75tL/DItotP66lUleD0sgQyNs3EM+USZPtkFkpJYnIyaX+qfH1zMR+nwLcOmbWHFAcyRBJXmDDDU3E3+UGEJ8DcLEktYOvnY5fGPdbjN5OMDbNdDYwwkC1Ggq/Cqbt1IwYNBCiuzxVtKIPo7oPFShg1mzkvmRTWD4MGygOUYlNTx9/x8OrnXrbj15tGRbrgjF3QE1HC87E464DUN77RZkNmV4ObW/sjo0LqubYeo5Je32oYk7Ys1akFQnPNxYgk+sFA2EvlvLdqDwK/GrV8KTB2OmhA0pgEFR505pCvHiPIA6WbShj2fffqNXUfFHHULo/sgHxI59Fk+lM5jjBQ+OiQuS41BoNhs02pLeuHsNBwRcqFu9MTrDKOtyIuMfbjG4MUTf6x6yleDRkGIkxZLQ0X6QDLOikEb0bVVxZ/xC3lrNfpgz6kRlXfopsBZK1AVrA3HnvhAeI+WjgsYxnHnLLuFddmKn6JpUaYn6GsS+k8gml0t82hi5d77dzVjycgdihk0nEwxbXLpSNuOSEIQu+TXnQZwpV8GOsnpHNYdvfAZIyQ7NZNQqO3O1hrA3qy3bbK87ZgwtkOg4/iZdVjBzEDHF6x2Hw/275WY/b9E3VL1yW+p5w1txG3tPb+wy7kVHmuW3SdmbP12y+a8aE="  # PYPI_PASSWORD.secret


addons:
    apt:
        packages:
            - xvfb      # install xvfb virtual framebuffer - this we need for WINE
            - winbind   # needed for WINE

services:   			# start services
  - xvfb    			# is needed for WINE on headless installation


matrix:
    include:

    - os: windows
      language: sh
      name: "Windows Python 3.8"

      # oddly a secure password under env: global: causes that choco fails
      # so we need to put the option : filter_secrets: false
      # this can be a security issue, check that You dont leak secrets here !
      filter_secrets: false
      before_install:
          - git clone https://github.com/bitranox/lib_bash.git /usr/local/lib_bash
          - chmod -R 0755 /usr/local/lib_bash
          - chmod -R +x /usr/local/lib_bash/*.sh
          - /usr/local/lib_bash/lib_retry.sh retry choco install python3
          - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"


    - os: linux
      language: python
      python: "3.6"
      before_install:
          - export MYPY_STRICT="True"
          - export BUILD_DOCS="False"
          - export DEPLOY_CHECK="True"
          - export DEPLOY="False"


    - os: linux
      language: python
      python: "3.7"
      before_install:
          - export MYPY_STRICT="True"
          - export BUILD_DOCS="False"
          - export DEPLOY_CHECK="True"
          - export DEPLOY="False"


    - os: linux
      language: python
      python: "3.8"
      before_install:
          - export MYPY_STRICT="True"
          - export BUILD_DOCS="True"
          - export DEPLOY_CHECK="True"
          - export DEPLOY="True"


    - os: linux
      language: python
      python: "3.8-dev"
      before_install:
          - export MYPY_STRICT="True"
          - export BUILD_DOCS="False"
          - export DEPLOY_CHECK="True"
          - export DEPLOY="False"


    - os: linux
      language: python
      python: "pypy3"
      before_install:
          - export MYPY_STRICT="False"
          - export BUILD_DOCS="False"
          - export DEPLOY_CHECK="True"
          - export DEPLOY="False"


    - os: osx
      language: sh
      name: "macOS 10.15.4"
      python: "3.8"
      osx_image: xcode11.5
      env:
        # on osx pip and python points to python 2.7 - therefore we have to use pip3 and python3 here
        - cPREFIX=""				# prefix before commands - used for wine, there the prefix is "wine"
        - cPYTHON="python3"			# command to launch python interpreter (its different on macOs, there we need python3)
        - cPIP="python3 -m pip"   	# command to launch pip (its different on macOs, there we need pip3)


install:
    - ${cPIP} install lib_travis
    - log_util --colortest
    - lib_travis install

script:
    - BRANCH=$(lib_travis get_branch)
    - log_util --level=NOTICE --banner "working on branch ${BRANCH}"
    - lib_travis script

after_success:
    - lib_travis after_success
    - lib_travis deploy

notifications:
  email:
    recipients:
        - bitranox@gmail.com
    # on_success default: change
    on_success: never
    on_failure: always
