language: python
group: travis_latest
dist: xenial

sudo: false

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7.1'     # 2019-03-25 latest Version
- '3.7-dev'   # 2018-03-25 development Version
# - '3.8-dev'   # 2019-03-28 does not exist now
# - 'nightly'   # 2019-03-28 does not exist now
- 'pypy2.7-6.0'
- 'pypy3.5-6.0'

### install xvfb virtual framebuffer - start commands with xvfb-run <command> - this we need for WINE
addons:
  apt:
    packages:
      - xvfb

matrix:
  include:

  - os: linux
    language: sh
    name: "WINE32 Python 3.7.3"
    env:
      WINEARCH=win32
      WINEPREFIX=${HOME}/wine/wine32

    before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - chmod 755 ./*.sh    # make shell scripts executable, just in case.
    - ./install_wine.sh
    - ./install_wine_machine_32bit.sh
    install:
      - wine c:/Python37-32/python -m pip install --upgrade pip

    script:
      - echo "Test Application will happen here"

  - os: linux
    language: sh
    name: "WINE64 Python 3.7.3"
    before_install:
    - chmod 755 ./*.sh    # make shell scripts executable, just in case.
    - ./install_wine.sh
    - ./install_wine_machine_64bit.sh
    install:
      - echo "Install Application will happen here"
    script:
      - echo "Test Application will happen here"

  - os: osx
    language: sh
    name: "osX Python 2.7"

  - os: osx
    language: sh
    name: "osX Python 3.6"

  - os: windows
    language: sh
    name: "Windows Python 2.7"
    before_install:
    - choco install python2
    - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    - python -m pip install --upgrade pip

  - os: windows
    language: sh
    name: "Windows Python 3.7"
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - python -m pip install --upgrade pip

before_install:
- pip install --upgrade pip

install:
- if [[ $TRAVIS_PYTHON_VERSION == pypy3.5-6.0 ]]; then pip install "pytest-cov==2.6.0"; fi
- pip install codecov pytest pytest-pep8 pytest-cov dill
- pip install -e .

script:
  - py.test --pep8 --cov

after_success:

- coverage report
- codecov
